### ISSUE TITLE
TrayOutrasEmpresas - Erro String Conexão

### ISSUE THREAD

**Issue by vinicius-campelo** [vinicius-campelo/mapas-leaflet#1]
**Erro:**
Boa Tarde! O Serviço do Tray != 771, não esta importando as vendas vi aqui no nos eventos do windows, que esta dando um erro a 771 esta ok, mas a 646(Gestaotextil2) não.

```
Faulting application name: TrayIntegracao.exe, version: 1.0.0.1, time stamp: 0x63320c01
Faulting module name: KERNELBASE.dll, version: 10.0.17763.1192, time stamp: 0x7889407f
Exception code: 0xe0434352
Fault offset: 0x0000000000039709
Faulting process id: 0x3f68
Faulting application start time: 0x01d91532b2ae7a1d
Faulting application path: C:\ServiceTray\TrayIntegracao.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 63acc9b1-f7d4-4bae-84a2-64aabb4b7d11
Faulting package full name: 
Faulting package-relative application ID: 

Application: TrayIntegracao.exe
CoreCLR Version: 4.700.22.47601
.NET Core Version: 3.1.30
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.WaitForShutdownAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at TrayIntegracao.Program.Main(String[] args) in C:\Users\VINICIUS\Desktop\Sistemas WIKI\ServicoTray\TrayIntegracao\Program.cs:line 14
´´´

**Comment by vinicius-campelo** [comment]
FINALIZADO!
